.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - /kaniko/executor 
      --context "${CI_PROJECT_DIR}" 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "registry:5000/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}" 
      --insecure
      --insecure-registry="${CI_REGISTRY}"
      --skip-tls-verify
      --skip-tls-verify-registry="${CI_REGISTRY}"
      --ignore-path=/product_uuid
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

.build_merge_request:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - /kaniko/executor 
      --context "${CI_PROJECT_DIR}" 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "registry:5000/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}"  
      --insecure
      --insecure-registry="${CI_REGISTRY}"
      --skip-tls-verify
      --skip-tls-verify-registry="${CI_REGISTRY}"
      --ignore-path=/product_uuid
      --no-push
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

build:
  extends: .build

build_merge_request:
  extends: .build_merge_request
