.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - env
    - echo "$CI_REGISTRY"
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY_PASSWORD"
    - export TIMESTAMP=$(date +%Y%m%d%H%M%S)
    - echo $TIMESTAMP > build_timestamp.txt
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor 
      --context "${CI_PROJECT_DIR}" 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}" 
      --insecure
      --insecure-registry="${CI_REGISTRY}"
      --skip-tls-verify
      --skip-tls-verify-registry="${CI_REGISTRY}"
      --ignore-path=/product_uuid
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

.build_merge_request:
  stage: build
  image: bitnami/minideb:latest
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor 
      --context "${CI_PROJECT_DIR}" 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" 
      --destination "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}" 
      --insecure
      --insecure-registry="${CI_REGISTRY}"
      --skip-tls-verify
      --skip-tls-verify-registry="${CI_REGISTRY}"
      --ignore-path=/product_uuid
      --no-push
  rules:
    - if: $CI_MERGE_REQUEST_ID

build:
  extends: .build

build_merge_request:
  extends: .build_merge_request