
.deploy:
  image: bitnami/kubectl:latest
  script:
    - cd $CI_PROJECT_DIR/k8s/cluster/${CI_ENVIRONMENT_NAME}
    - sed -i "s/IMAGE_TAG/\"$CI_PIPELINE_ID\"/g" kustomization.yml
    - sed -i "s/HOSTNAME/${MY_HOSTNAME}/g" $CI_PROJECT_DIR/k8s/base/deployment.yml
    - kubectl apply -k . -n ${KUBERNETES_NAMESPACE}
  dependencies:
    - build

.deploy_dev:
  extends: .deploy
  variables:
    KUBERNETES_NAMESPACE: ${KUBERNETES_NAMESPACE_DEV}
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  environment:
    name: dev

.deploy_stg:
  extends: .deploy
  variables:
    KUBERNETES_NAMESPACE: ${KUBERNETES_NAMESPACE_STG}
  rules:
    - if: $CI_COMMIT_BRANCH == "stg"
      when: manual
  environment:
    name: stg

.deploy_prod:
  extends: .deploy
  variables:
    KUBERNETES_NAMESPACE: ${KUBERNETES_NAMESPACE_PROD}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  environment:
    name: prod