ci_access:
  projects:
    - id: "ententeich/ci-cd"
    - id: "ententeich/frontente"
    - id: "ententeich/backente"
  groups:
    - id: ententeich

observability:
  logging:
    level: debug
    grpc_level: warn
