---
- name: Install common dependencies (Linux)
  package:
    name:
      - curl
      - git
      - python3-pip
      - python-gitlab
    state: present
  when: ansible_system != "Darwin"

- name: Copy .env.example to .env if .env doesn't exist
  become: no
  copy:
    src: "{{ playbook_dir }}/../../.env.example"
    dest: "{{ playbook_dir }}/../../.env"
    force: no
  register: env_file_copied

- name: Inform user about .env file creation
  become: no
  debug:
    msg: ".env file has been created from .env.example. Please review and update the values as needed."
  when: env_file_copied.changed
