---
- name: Install Homebrew (macOS)
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew

- name: Install macOS dependencies
  community.general.homebrew:
    name:
      - curl
      - git
      - python@3
      - python-gitlab
    state: present

- name: Install Docker (macOS)
  community.general.homebrew_cask:
    name: docker
    state: present

- name: Ensure Docker is running (macOS)
  command: open -a Docker

- name: Wait for Docker to start
  wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 60

- name: Get current user
  command: whoami
  register: current_user
  changed_when: false

- name: Ensure user is in docker group
  user:
    name: "{{ current_user.stdout }}"
    groups: docker
    append: yes
  become: yes

- name: Install kubectl (macOS)
  homebrew:
    name: kubectl
    state: present

- name: Install k9s (macOS)
  homebrew:
    name: derailed/k9s/k9s
    state: present

- name: Install KinD (macOS)
  homebrew:
    name: kind
    state: present

- name: Install OpenTofu (macOS)
  community.general.homebrew:
    name: opentofu
    state: present

- name: Reload user groups
  shell: |
    if [ -x "$(command -v newgrp)" ]; then
      newgrp docker
    else
      exec su -l $USER
    fi
  args:
    executable: /bin/bash